### YamlMime:ManagedReference
items:
- uid: Vasont.Inspire.Models.Configuration.ElementModel
  commentId: T:Vasont.Inspire.Models.Configuration.ElementModel
  id: ElementModel
  parent: Vasont.Inspire.Models.Configuration
  children:
  - Vasont.Inspire.Models.Configuration.ElementModel.ElementDisplayName
  - Vasont.Inspire.Models.Configuration.ElementModel.ElementId
  - Vasont.Inspire.Models.Configuration.ElementModel.ElementName
  - Vasont.Inspire.Models.Configuration.ElementModel.NeedsId
  - Vasont.Inspire.Models.Configuration.ElementModel.SchemaStandardId
  langs:
  - csharp
  - vb
  name: ElementModel
  nameWithType: ElementModel
  fullName: Vasont.Inspire.Models.Configuration.ElementModel
  type: Class
  source:
    remote:
      path: src/Configuration/ElementModel.cs
      branch: develop
      repo: https://github.com/vasont-systems/Vasont.Inspire.Models.git
    id: ElementModel
    path: Configuration/ElementModel.cs
    startLine: 10
  assemblies:
  - Vasont.Inspire.Models
  namespace: Vasont.Inspire.Models.Configuration
  summary: "\nThis class represents an element within the system and is to be used for interaction with application user interfaces.\n"
  example: []
  syntax:
    content: public class ElementModel
    content.vb: Public Class ElementModel
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Vasont.Inspire.Models.Configuration.ElementModel.ElementId
  commentId: P:Vasont.Inspire.Models.Configuration.ElementModel.ElementId
  id: ElementId
  parent: Vasont.Inspire.Models.Configuration.ElementModel
  langs:
  - csharp
  - vb
  name: ElementId
  nameWithType: ElementModel.ElementId
  fullName: Vasont.Inspire.Models.Configuration.ElementModel.ElementId
  type: Property
  source:
    remote:
      path: src/Configuration/ElementModel.cs
      branch: develop
      repo: https://github.com/vasont-systems/Vasont.Inspire.Models.git
    id: ElementId
    path: Configuration/ElementModel.cs
    startLine: 15
  assemblies:
  - Vasont.Inspire.Models
  namespace: Vasont.Inspire.Models.Configuration
  summary: "\nGets or sets the Id of the element.\n"
  example: []
  syntax:
    content: public long ElementId { get; set; }
    parameters: []
    return:
      type: System.Int64
    content.vb: Public Property ElementId As Long
  overload: Vasont.Inspire.Models.Configuration.ElementModel.ElementId*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Vasont.Inspire.Models.Configuration.ElementModel.ElementName
  commentId: P:Vasont.Inspire.Models.Configuration.ElementModel.ElementName
  id: ElementName
  parent: Vasont.Inspire.Models.Configuration.ElementModel
  langs:
  - csharp
  - vb
  name: ElementName
  nameWithType: ElementModel.ElementName
  fullName: Vasont.Inspire.Models.Configuration.ElementModel.ElementName
  type: Property
  source:
    remote:
      path: src/Configuration/ElementModel.cs
      branch: develop
      repo: https://github.com/vasont-systems/Vasont.Inspire.Models.git
    id: ElementName
    path: Configuration/ElementModel.cs
    startLine: 20
  assemblies:
  - Vasont.Inspire.Models
  namespace: Vasont.Inspire.Models.Configuration
  summary: "\nGets or sets the name of the element.\n"
  example: []
  syntax:
    content: public string ElementName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ElementName As String
  overload: Vasont.Inspire.Models.Configuration.ElementModel.ElementName*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Vasont.Inspire.Models.Configuration.ElementModel.ElementDisplayName
  commentId: P:Vasont.Inspire.Models.Configuration.ElementModel.ElementDisplayName
  id: ElementDisplayName
  parent: Vasont.Inspire.Models.Configuration.ElementModel
  langs:
  - csharp
  - vb
  name: ElementDisplayName
  nameWithType: ElementModel.ElementDisplayName
  fullName: Vasont.Inspire.Models.Configuration.ElementModel.ElementDisplayName
  type: Property
  source:
    remote:
      path: src/Configuration/ElementModel.cs
      branch: develop
      repo: https://github.com/vasont-systems/Vasont.Inspire.Models.git
    id: ElementDisplayName
    path: Configuration/ElementModel.cs
    startLine: 25
  assemblies:
  - Vasont.Inspire.Models
  namespace: Vasont.Inspire.Models.Configuration
  summary: "\nGets or sets the display name of the element.\n"
  example: []
  syntax:
    content: public string ElementDisplayName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ElementDisplayName As String
  overload: Vasont.Inspire.Models.Configuration.ElementModel.ElementDisplayName*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Vasont.Inspire.Models.Configuration.ElementModel.NeedsId
  commentId: P:Vasont.Inspire.Models.Configuration.ElementModel.NeedsId
  id: NeedsId
  parent: Vasont.Inspire.Models.Configuration.ElementModel
  langs:
  - csharp
  - vb
  name: NeedsId
  nameWithType: ElementModel.NeedsId
  fullName: Vasont.Inspire.Models.Configuration.ElementModel.NeedsId
  type: Property
  source:
    remote:
      path: src/Configuration/ElementModel.cs
      branch: develop
      repo: https://github.com/vasont-systems/Vasont.Inspire.Models.git
    id: NeedsId
    path: Configuration/ElementModel.cs
    startLine: 30
  assemblies:
  - Vasont.Inspire.Models
  namespace: Vasont.Inspire.Models.Configuration
  summary: "\nGets or sets a value indicating whether the element should have an ID.\n"
  example: []
  syntax:
    content: public bool NeedsId { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property NeedsId As Boolean
  overload: Vasont.Inspire.Models.Configuration.ElementModel.NeedsId*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Vasont.Inspire.Models.Configuration.ElementModel.SchemaStandardId
  commentId: P:Vasont.Inspire.Models.Configuration.ElementModel.SchemaStandardId
  id: SchemaStandardId
  parent: Vasont.Inspire.Models.Configuration.ElementModel
  langs:
  - csharp
  - vb
  name: SchemaStandardId
  nameWithType: ElementModel.SchemaStandardId
  fullName: Vasont.Inspire.Models.Configuration.ElementModel.SchemaStandardId
  type: Property
  source:
    remote:
      path: src/Configuration/ElementModel.cs
      branch: develop
      repo: https://github.com/vasont-systems/Vasont.Inspire.Models.git
    id: SchemaStandardId
    path: Configuration/ElementModel.cs
    startLine: 35
  assemblies:
  - Vasont.Inspire.Models
  namespace: Vasont.Inspire.Models.Configuration
  summary: "\nGets or sets the display name of the element.\n"
  example: []
  syntax:
    content: public long SchemaStandardId { get; set; }
    parameters: []
    return:
      type: System.Int64
    content.vb: Public Property SchemaStandardId As Long
  overload: Vasont.Inspire.Models.Configuration.ElementModel.SchemaStandardId*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Vasont.Inspire.Models.Configuration
  commentId: N:Vasont.Inspire.Models.Configuration
  name: Vasont.Inspire.Models.Configuration
  nameWithType: Vasont.Inspire.Models.Configuration
  fullName: Vasont.Inspire.Models.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Vasont.Inspire.Models.Configuration.ElementModel.ElementId*
  commentId: Overload:Vasont.Inspire.Models.Configuration.ElementModel.ElementId
  name: ElementId
  nameWithType: ElementModel.ElementId
  fullName: Vasont.Inspire.Models.Configuration.ElementModel.ElementId
- uid: System.Int64
  commentId: T:System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: Vasont.Inspire.Models.Configuration.ElementModel.ElementName*
  commentId: Overload:Vasont.Inspire.Models.Configuration.ElementModel.ElementName
  name: ElementName
  nameWithType: ElementModel.ElementName
  fullName: Vasont.Inspire.Models.Configuration.ElementModel.ElementName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Vasont.Inspire.Models.Configuration.ElementModel.ElementDisplayName*
  commentId: Overload:Vasont.Inspire.Models.Configuration.ElementModel.ElementDisplayName
  name: ElementDisplayName
  nameWithType: ElementModel.ElementDisplayName
  fullName: Vasont.Inspire.Models.Configuration.ElementModel.ElementDisplayName
- uid: Vasont.Inspire.Models.Configuration.ElementModel.NeedsId*
  commentId: Overload:Vasont.Inspire.Models.Configuration.ElementModel.NeedsId
  name: NeedsId
  nameWithType: ElementModel.NeedsId
  fullName: Vasont.Inspire.Models.Configuration.ElementModel.NeedsId
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Vasont.Inspire.Models.Configuration.ElementModel.SchemaStandardId*
  commentId: Overload:Vasont.Inspire.Models.Configuration.ElementModel.SchemaStandardId
  name: SchemaStandardId
  nameWithType: ElementModel.SchemaStandardId
  fullName: Vasont.Inspire.Models.Configuration.ElementModel.SchemaStandardId
