### YamlMime:ManagedReference
items:
- uid: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationElementModeRole
  commentId: T:Vasont.Inspire.Models.Components.Schema.ComponentConfigurationElementModeRole
  id: ComponentConfigurationElementModeRole
  parent: Vasont.Inspire.Models.Components.Schema
  children:
  - Vasont.Inspire.Models.Components.Schema.ComponentConfigurationElementModeRole.Container
  - Vasont.Inspire.Models.Components.Schema.ComponentConfigurationElementModeRole.Empty
  - Vasont.Inspire.Models.Components.Schema.ComponentConfigurationElementModeRole.Mixed
  - Vasont.Inspire.Models.Components.Schema.ComponentConfigurationElementModeRole.MixedContainer
  - Vasont.Inspire.Models.Components.Schema.ComponentConfigurationElementModeRole.MixedWithStyling
  langs:
  - csharp
  - vb
  name: ComponentConfigurationElementModeRole
  nameWithType: ComponentConfigurationElementModeRole
  fullName: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationElementModeRole
  type: Enum
  source:
    remote:
      path: src/Components/Schema/ComponentElementModel.cs
      branch: feature/57491ComponentCompletenessEnhancements
      repo: https://github.com/vasont-systems/Vasont.Inspire.Models.git
    id: ComponentConfigurationElementModeRole
    path: Components/Schema/ComponentElementModel.cs
    startLine: 14
  assemblies:
  - Vasont.Inspire.Models
  namespace: Vasont.Inspire.Models.Components.Schema
  summary: "\nContains an enumerated list of element mode roles.\n"
  example: []
  syntax:
    content: >-
      [JsonConverter(typeof(StringEnumConverter))]

      public enum ComponentConfigurationElementModeRole
    content.vb: >-
      <JsonConverter(GetType(StringEnumConverter))>

      Public Enum ComponentConfigurationElementModeRole
  attributes:
  - type: Newtonsoft.Json.JsonConverterAttribute
    ctor: Newtonsoft.Json.JsonConverterAttribute.#ctor(System.Type)
    arguments:
    - type: System.Type
      value: Newtonsoft.Json.Converters.StringEnumConverter
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationElementModeRole.Empty
  commentId: F:Vasont.Inspire.Models.Components.Schema.ComponentConfigurationElementModeRole.Empty
  id: Empty
  parent: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationElementModeRole
  langs:
  - csharp
  - vb
  name: Empty
  nameWithType: ComponentConfigurationElementModeRole.Empty
  fullName: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationElementModeRole.Empty
  type: Field
  source:
    remote:
      path: src/Components/Schema/ComponentElementModel.cs
      branch: feature/57491ComponentCompletenessEnhancements
      repo: https://github.com/vasont-systems/Vasont.Inspire.Models.git
    id: Empty
    path: Components/Schema/ComponentElementModel.cs
    startLine: 20
  assemblies:
  - Vasont.Inspire.Models
  namespace: Vasont.Inspire.Models.Components.Schema
  summary: "\nElement cannot contain any sub-elements or text.\n"
  example: []
  syntax:
    content: Empty = 0
    return:
      type: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationElementModeRole
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationElementModeRole.Container
  commentId: F:Vasont.Inspire.Models.Components.Schema.ComponentConfigurationElementModeRole.Container
  id: Container
  parent: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationElementModeRole
  langs:
  - csharp
  - vb
  name: Container
  nameWithType: ComponentConfigurationElementModeRole.Container
  fullName: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationElementModeRole.Container
  type: Field
  source:
    remote:
      path: src/Components/Schema/ComponentElementModel.cs
      branch: feature/57491ComponentCompletenessEnhancements
      repo: https://github.com/vasont-systems/Vasont.Inspire.Models.git
    id: Container
    path: Components/Schema/ComponentElementModel.cs
    startLine: 25
  assemblies:
  - Vasont.Inspire.Models
  namespace: Vasont.Inspire.Models.Components.Schema
  summary: "\nElement can only contain block elements.\n"
  example: []
  syntax:
    content: Container = 1
    return:
      type: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationElementModeRole
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationElementModeRole.Mixed
  commentId: F:Vasont.Inspire.Models.Components.Schema.ComponentConfigurationElementModeRole.Mixed
  id: Mixed
  parent: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationElementModeRole
  langs:
  - csharp
  - vb
  name: Mixed
  nameWithType: ComponentConfigurationElementModeRole.Mixed
  fullName: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationElementModeRole.Mixed
  type: Field
  source:
    remote:
      path: src/Components/Schema/ComponentElementModel.cs
      branch: feature/57491ComponentCompletenessEnhancements
      repo: https://github.com/vasont-systems/Vasont.Inspire.Models.git
    id: Mixed
    path: Components/Schema/ComponentElementModel.cs
    startLine: 30
  assemblies:
  - Vasont.Inspire.Models
  namespace: Vasont.Inspire.Models.Components.Schema
  summary: "\nElement can contain text with inline elements\n"
  example: []
  syntax:
    content: Mixed = 2
    return:
      type: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationElementModeRole
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationElementModeRole.MixedWithStyling
  commentId: F:Vasont.Inspire.Models.Components.Schema.ComponentConfigurationElementModeRole.MixedWithStyling
  id: MixedWithStyling
  parent: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationElementModeRole
  langs:
  - csharp
  - vb
  name: MixedWithStyling
  nameWithType: ComponentConfigurationElementModeRole.MixedWithStyling
  fullName: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationElementModeRole.MixedWithStyling
  type: Field
  source:
    remote:
      path: src/Components/Schema/ComponentElementModel.cs
      branch: feature/57491ComponentCompletenessEnhancements
      repo: https://github.com/vasont-systems/Vasont.Inspire.Models.git
    id: MixedWithStyling
    path: Components/Schema/ComponentElementModel.cs
    startLine: 35
  assemblies:
  - Vasont.Inspire.Models
  namespace: Vasont.Inspire.Models.Components.Schema
  summary: "\nElement can contain block elements, and text with in-line elements for styling.\n"
  example: []
  syntax:
    content: MixedWithStyling = 3
    return:
      type: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationElementModeRole
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationElementModeRole.MixedContainer
  commentId: F:Vasont.Inspire.Models.Components.Schema.ComponentConfigurationElementModeRole.MixedContainer
  id: MixedContainer
  parent: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationElementModeRole
  langs:
  - csharp
  - vb
  name: MixedContainer
  nameWithType: ComponentConfigurationElementModeRole.MixedContainer
  fullName: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationElementModeRole.MixedContainer
  type: Field
  source:
    remote:
      path: src/Components/Schema/ComponentElementModel.cs
      branch: feature/57491ComponentCompletenessEnhancements
      repo: https://github.com/vasont-systems/Vasont.Inspire.Models.git
    id: MixedContainer
    path: Components/Schema/ComponentElementModel.cs
    startLine: 40
  assemblies:
  - Vasont.Inspire.Models
  namespace: Vasont.Inspire.Models.Components.Schema
  summary: "\nElement can contain block elements and text with inline elements\n"
  example: []
  syntax:
    content: MixedContainer = 4
    return:
      type: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationElementModeRole
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Vasont.Inspire.Models.Components.Schema
  commentId: N:Vasont.Inspire.Models.Components.Schema
  name: Vasont.Inspire.Models.Components.Schema
  nameWithType: Vasont.Inspire.Models.Components.Schema
  fullName: Vasont.Inspire.Models.Components.Schema
- uid: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationElementModeRole
  commentId: T:Vasont.Inspire.Models.Components.Schema.ComponentConfigurationElementModeRole
  parent: Vasont.Inspire.Models.Components.Schema
  name: ComponentConfigurationElementModeRole
  nameWithType: ComponentConfigurationElementModeRole
  fullName: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationElementModeRole
