### YamlMime:ManagedReference
items:
- uid: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType
  commentId: T:Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType
  id: ComponentConfigurationAttributeType
  parent: Vasont.Inspire.Models.Components.Schema
  children:
  - Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType.Boolean
  - Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType.Component
  - Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType.Date
  - Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType.DateTime
  - Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType.Identity
  - Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType.Multiselect
  - Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType.Number
  - Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType.String
  langs:
  - csharp
  - vb
  name: ComponentConfigurationAttributeType
  nameWithType: ComponentConfigurationAttributeType
  fullName: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType
  type: Enum
  source:
    remote:
      path: src/Components/Schema/ComponentAttributeModel.cs
      branch: feature/58277RemoveUnusedModelsPart2
      repo: https://github.com/vasont-systems/Vasont.Inspire.Models.git
    id: ComponentConfigurationAttributeType
    path: Components/Schema/ComponentAttributeModel.cs
    startLine: 14
  assemblies:
  - Vasont.Inspire.Models
  namespace: Vasont.Inspire.Models.Components.Schema
  summary: "\nContains an enumerated list of map configuration attribute types used for determining how the attribute value field shall be rendered in the application.\n"
  example: []
  syntax:
    content: >-
      [JsonConverter(typeof(StringEnumConverter))]

      public enum ComponentConfigurationAttributeType
    content.vb: >-
      <JsonConverter(GetType(StringEnumConverter))>

      Public Enum ComponentConfigurationAttributeType
  attributes:
  - type: Newtonsoft.Json.JsonConverterAttribute
    ctor: Newtonsoft.Json.JsonConverterAttribute.#ctor(System.Type)
    arguments:
    - type: System.Type
      value: Newtonsoft.Json.Converters.StringEnumConverter
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType.Identity
  commentId: F:Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType.Identity
  id: Identity
  parent: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType
  langs:
  - csharp
  - vb
  name: Identity
  nameWithType: ComponentConfigurationAttributeType.Identity
  fullName: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType.Identity
  type: Field
  source:
    remote:
      path: src/Components/Schema/ComponentAttributeModel.cs
      branch: feature/58277RemoveUnusedModelsPart2
      repo: https://github.com/vasont-systems/Vasont.Inspire.Models.git
    id: Identity
    path: Components/Schema/ComponentAttributeModel.cs
    startLine: 20
  assemblies:
  - Vasont.Inspire.Models
  namespace: Vasont.Inspire.Models.Components.Schema
  summary: "\nThe attribute is an identity type containing a unique identity for the element.\n"
  example: []
  syntax:
    content: Identity = 0
    return:
      type: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType.String
  commentId: F:Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType.String
  id: String
  parent: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType
  langs:
  - csharp
  - vb
  name: String
  nameWithType: ComponentConfigurationAttributeType.String
  fullName: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType.String
  type: Field
  source:
    remote:
      path: src/Components/Schema/ComponentAttributeModel.cs
      branch: feature/58277RemoveUnusedModelsPart2
      repo: https://github.com/vasont-systems/Vasont.Inspire.Models.git
    id: String
    path: Components/Schema/ComponentAttributeModel.cs
    startLine: 25
  assemblies:
  - Vasont.Inspire.Models
  namespace: Vasont.Inspire.Models.Components.Schema
  summary: "\nThe attribute contains a general string value.\n"
  example: []
  syntax:
    content: String = 1
    return:
      type: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType.Boolean
  commentId: F:Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType.Boolean
  id: Boolean
  parent: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType
  langs:
  - csharp
  - vb
  name: Boolean
  nameWithType: ComponentConfigurationAttributeType.Boolean
  fullName: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType.Boolean
  type: Field
  source:
    remote:
      path: src/Components/Schema/ComponentAttributeModel.cs
      branch: feature/58277RemoveUnusedModelsPart2
      repo: https://github.com/vasont-systems/Vasont.Inspire.Models.git
    id: Boolean
    path: Components/Schema/ComponentAttributeModel.cs
    startLine: 30
  assemblies:
  - Vasont.Inspire.Models
  namespace: Vasont.Inspire.Models.Components.Schema
  summary: "\nThe attribute contains a boolean value.\n"
  example: []
  syntax:
    content: Boolean = 2
    return:
      type: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType.Date
  commentId: F:Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType.Date
  id: Date
  parent: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType
  langs:
  - csharp
  - vb
  name: Date
  nameWithType: ComponentConfigurationAttributeType.Date
  fullName: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType.Date
  type: Field
  source:
    remote:
      path: src/Components/Schema/ComponentAttributeModel.cs
      branch: feature/58277RemoveUnusedModelsPart2
      repo: https://github.com/vasont-systems/Vasont.Inspire.Models.git
    id: Date
    path: Components/Schema/ComponentAttributeModel.cs
    startLine: 35
  assemblies:
  - Vasont.Inspire.Models
  namespace: Vasont.Inspire.Models.Components.Schema
  summary: "\nThe attribute contains a date value.\n"
  example: []
  syntax:
    content: Date = 3
    return:
      type: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType.DateTime
  commentId: F:Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType.DateTime
  id: DateTime
  parent: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType
  langs:
  - csharp
  - vb
  name: DateTime
  nameWithType: ComponentConfigurationAttributeType.DateTime
  fullName: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType.DateTime
  type: Field
  source:
    remote:
      path: src/Components/Schema/ComponentAttributeModel.cs
      branch: feature/58277RemoveUnusedModelsPart2
      repo: https://github.com/vasont-systems/Vasont.Inspire.Models.git
    id: DateTime
    path: Components/Schema/ComponentAttributeModel.cs
    startLine: 40
  assemblies:
  - Vasont.Inspire.Models
  namespace: Vasont.Inspire.Models.Components.Schema
  summary: "\nThe attribute contains a date time value.\n"
  example: []
  syntax:
    content: DateTime = 4
    return:
      type: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType.Number
  commentId: F:Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType.Number
  id: Number
  parent: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType
  langs:
  - csharp
  - vb
  name: Number
  nameWithType: ComponentConfigurationAttributeType.Number
  fullName: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType.Number
  type: Field
  source:
    remote:
      path: src/Components/Schema/ComponentAttributeModel.cs
      branch: feature/58277RemoveUnusedModelsPart2
      repo: https://github.com/vasont-systems/Vasont.Inspire.Models.git
    id: Number
    path: Components/Schema/ComponentAttributeModel.cs
    startLine: 45
  assemblies:
  - Vasont.Inspire.Models
  namespace: Vasont.Inspire.Models.Components.Schema
  summary: "\nThe attribute contains a number.\n"
  example: []
  syntax:
    content: Number = 5
    return:
      type: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType.Component
  commentId: F:Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType.Component
  id: Component
  parent: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType
  langs:
  - csharp
  - vb
  name: Component
  nameWithType: ComponentConfigurationAttributeType.Component
  fullName: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType.Component
  type: Field
  source:
    remote:
      path: src/Components/Schema/ComponentAttributeModel.cs
      branch: feature/58277RemoveUnusedModelsPart2
      repo: https://github.com/vasont-systems/Vasont.Inspire.Models.git
    id: Component
    path: Components/Schema/ComponentAttributeModel.cs
    startLine: 50
  assemblies:
  - Vasont.Inspire.Models
  namespace: Vasont.Inspire.Models.Components.Schema
  summary: "\nThe attribute shall point to a component.\n"
  example: []
  syntax:
    content: Component = 6
    return:
      type: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType.Multiselect
  commentId: F:Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType.Multiselect
  id: Multiselect
  parent: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType
  langs:
  - csharp
  - vb
  name: Multiselect
  nameWithType: ComponentConfigurationAttributeType.Multiselect
  fullName: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType.Multiselect
  type: Field
  source:
    remote:
      path: src/Components/Schema/ComponentAttributeModel.cs
      branch: feature/58277RemoveUnusedModelsPart2
      repo: https://github.com/vasont-systems/Vasont.Inspire.Models.git
    id: Multiselect
    path: Components/Schema/ComponentAttributeModel.cs
    startLine: 55
  assemblies:
  - Vasont.Inspire.Models
  namespace: Vasont.Inspire.Models.Components.Schema
  summary: "\nThe attribute allows for multiple value selections.\n"
  example: []
  syntax:
    content: Multiselect = 7
    return:
      type: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Vasont.Inspire.Models.Components.Schema
  commentId: N:Vasont.Inspire.Models.Components.Schema
  name: Vasont.Inspire.Models.Components.Schema
  nameWithType: Vasont.Inspire.Models.Components.Schema
  fullName: Vasont.Inspire.Models.Components.Schema
- uid: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType
  commentId: T:Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType
  parent: Vasont.Inspire.Models.Components.Schema
  name: ComponentConfigurationAttributeType
  nameWithType: ComponentConfigurationAttributeType
  fullName: Vasont.Inspire.Models.Components.Schema.ComponentConfigurationAttributeType
