### YamlMime:ManagedReference
items:
- uid: Vasont.Inspire.Models.Configuration.AttributeModel
  commentId: T:Vasont.Inspire.Models.Configuration.AttributeModel
  id: AttributeModel
  parent: Vasont.Inspire.Models.Configuration
  children:
  - Vasont.Inspire.Models.Configuration.AttributeModel.AttributeDisplayName
  - Vasont.Inspire.Models.Configuration.AttributeModel.AttributeId
  - Vasont.Inspire.Models.Configuration.AttributeModel.AttributeName
  - Vasont.Inspire.Models.Configuration.AttributeModel.Identifier
  - Vasont.Inspire.Models.Configuration.AttributeModel.Profiled
  - Vasont.Inspire.Models.Configuration.AttributeModel.SchemaStandardKeyName
  langs:
  - csharp
  - vb
  name: AttributeModel
  nameWithType: AttributeModel
  fullName: Vasont.Inspire.Models.Configuration.AttributeModel
  type: Class
  source:
    remote:
      path: src/Configuration/AttributeModel.cs
      branch: feature/58761TranslationConfigurationsPart3Models
      repo: https://github.com/vasont-systems/Vasont.Inspire.Models.git
    id: AttributeModel
    path: Configuration/AttributeModel.cs
    startLine: 10
  assemblies:
  - Vasont.Inspire.Models
  namespace: Vasont.Inspire.Models.Configuration
  summary: "\nThis class represents an attribute within the system and is to be used for interaction with application user interfaces.\n"
  example: []
  syntax:
    content: public class AttributeModel
    content.vb: Public Class AttributeModel
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Vasont.Inspire.Models.Configuration.AttributeModel.AttributeId
  commentId: P:Vasont.Inspire.Models.Configuration.AttributeModel.AttributeId
  id: AttributeId
  parent: Vasont.Inspire.Models.Configuration.AttributeModel
  langs:
  - csharp
  - vb
  name: AttributeId
  nameWithType: AttributeModel.AttributeId
  fullName: Vasont.Inspire.Models.Configuration.AttributeModel.AttributeId
  type: Property
  source:
    remote:
      path: src/Configuration/AttributeModel.cs
      branch: feature/58761TranslationConfigurationsPart3Models
      repo: https://github.com/vasont-systems/Vasont.Inspire.Models.git
    id: AttributeId
    path: Configuration/AttributeModel.cs
    startLine: 15
  assemblies:
  - Vasont.Inspire.Models
  namespace: Vasont.Inspire.Models.Configuration
  summary: "\nGets or sets the Id of the element.\n"
  example: []
  syntax:
    content: public long AttributeId { get; set; }
    parameters: []
    return:
      type: System.Int64
    content.vb: Public Property AttributeId As Long
  overload: Vasont.Inspire.Models.Configuration.AttributeModel.AttributeId*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Vasont.Inspire.Models.Configuration.AttributeModel.AttributeName
  commentId: P:Vasont.Inspire.Models.Configuration.AttributeModel.AttributeName
  id: AttributeName
  parent: Vasont.Inspire.Models.Configuration.AttributeModel
  langs:
  - csharp
  - vb
  name: AttributeName
  nameWithType: AttributeModel.AttributeName
  fullName: Vasont.Inspire.Models.Configuration.AttributeModel.AttributeName
  type: Property
  source:
    remote:
      path: src/Configuration/AttributeModel.cs
      branch: feature/58761TranslationConfigurationsPart3Models
      repo: https://github.com/vasont-systems/Vasont.Inspire.Models.git
    id: AttributeName
    path: Configuration/AttributeModel.cs
    startLine: 20
  assemblies:
  - Vasont.Inspire.Models
  namespace: Vasont.Inspire.Models.Configuration
  summary: "\nGets or sets the name of the element.\n"
  example: []
  syntax:
    content: public string AttributeName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property AttributeName As String
  overload: Vasont.Inspire.Models.Configuration.AttributeModel.AttributeName*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Vasont.Inspire.Models.Configuration.AttributeModel.AttributeDisplayName
  commentId: P:Vasont.Inspire.Models.Configuration.AttributeModel.AttributeDisplayName
  id: AttributeDisplayName
  parent: Vasont.Inspire.Models.Configuration.AttributeModel
  langs:
  - csharp
  - vb
  name: AttributeDisplayName
  nameWithType: AttributeModel.AttributeDisplayName
  fullName: Vasont.Inspire.Models.Configuration.AttributeModel.AttributeDisplayName
  type: Property
  source:
    remote:
      path: src/Configuration/AttributeModel.cs
      branch: feature/58761TranslationConfigurationsPart3Models
      repo: https://github.com/vasont-systems/Vasont.Inspire.Models.git
    id: AttributeDisplayName
    path: Configuration/AttributeModel.cs
    startLine: 25
  assemblies:
  - Vasont.Inspire.Models
  namespace: Vasont.Inspire.Models.Configuration
  summary: "\nGets or sets the display name of the element.\n"
  example: []
  syntax:
    content: public string AttributeDisplayName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property AttributeDisplayName As String
  overload: Vasont.Inspire.Models.Configuration.AttributeModel.AttributeDisplayName*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Vasont.Inspire.Models.Configuration.AttributeModel.Profiled
  commentId: P:Vasont.Inspire.Models.Configuration.AttributeModel.Profiled
  id: Profiled
  parent: Vasont.Inspire.Models.Configuration.AttributeModel
  langs:
  - csharp
  - vb
  name: Profiled
  nameWithType: AttributeModel.Profiled
  fullName: Vasont.Inspire.Models.Configuration.AttributeModel.Profiled
  type: Property
  source:
    remote:
      path: src/Configuration/AttributeModel.cs
      branch: feature/58761TranslationConfigurationsPart3Models
      repo: https://github.com/vasont-systems/Vasont.Inspire.Models.git
    id: Profiled
    path: Configuration/AttributeModel.cs
    startLine: 30
  assemblies:
  - Vasont.Inspire.Models
  namespace: Vasont.Inspire.Models.Configuration
  summary: "\nGets or sets a value indicating whether the attribute is a profiling attribute.\n"
  example: []
  syntax:
    content: public bool Profiled { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property Profiled As Boolean
  overload: Vasont.Inspire.Models.Configuration.AttributeModel.Profiled*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Vasont.Inspire.Models.Configuration.AttributeModel.Identifier
  commentId: P:Vasont.Inspire.Models.Configuration.AttributeModel.Identifier
  id: Identifier
  parent: Vasont.Inspire.Models.Configuration.AttributeModel
  langs:
  - csharp
  - vb
  name: Identifier
  nameWithType: AttributeModel.Identifier
  fullName: Vasont.Inspire.Models.Configuration.AttributeModel.Identifier
  type: Property
  source:
    remote:
      path: src/Configuration/AttributeModel.cs
      branch: feature/58761TranslationConfigurationsPart3Models
      repo: https://github.com/vasont-systems/Vasont.Inspire.Models.git
    id: Identifier
    path: Configuration/AttributeModel.cs
    startLine: 35
  assemblies:
  - Vasont.Inspire.Models
  namespace: Vasont.Inspire.Models.Configuration
  summary: "\nGets or sets a value indicating whether the attribute is an identifier.\n"
  example: []
  syntax:
    content: public bool Identifier { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property Identifier As Boolean
  overload: Vasont.Inspire.Models.Configuration.AttributeModel.Identifier*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Vasont.Inspire.Models.Configuration.AttributeModel.SchemaStandardKeyName
  commentId: P:Vasont.Inspire.Models.Configuration.AttributeModel.SchemaStandardKeyName
  id: SchemaStandardKeyName
  parent: Vasont.Inspire.Models.Configuration.AttributeModel
  langs:
  - csharp
  - vb
  name: SchemaStandardKeyName
  nameWithType: AttributeModel.SchemaStandardKeyName
  fullName: Vasont.Inspire.Models.Configuration.AttributeModel.SchemaStandardKeyName
  type: Property
  source:
    remote:
      path: src/Configuration/AttributeModel.cs
      branch: feature/58761TranslationConfigurationsPart3Models
      repo: https://github.com/vasont-systems/Vasont.Inspire.Models.git
    id: SchemaStandardKeyName
    path: Configuration/AttributeModel.cs
    startLine: 40
  assemblies:
  - Vasont.Inspire.Models
  namespace: Vasont.Inspire.Models.Configuration
  summary: "\nGets or sets the schema standard key name for the attribute.\n"
  example: []
  syntax:
    content: public string SchemaStandardKeyName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property SchemaStandardKeyName As String
  overload: Vasont.Inspire.Models.Configuration.AttributeModel.SchemaStandardKeyName*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Vasont.Inspire.Models.Configuration
  commentId: N:Vasont.Inspire.Models.Configuration
  name: Vasont.Inspire.Models.Configuration
  nameWithType: Vasont.Inspire.Models.Configuration
  fullName: Vasont.Inspire.Models.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Vasont.Inspire.Models.Configuration.AttributeModel.AttributeId*
  commentId: Overload:Vasont.Inspire.Models.Configuration.AttributeModel.AttributeId
  name: AttributeId
  nameWithType: AttributeModel.AttributeId
  fullName: Vasont.Inspire.Models.Configuration.AttributeModel.AttributeId
- uid: System.Int64
  commentId: T:System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: Vasont.Inspire.Models.Configuration.AttributeModel.AttributeName*
  commentId: Overload:Vasont.Inspire.Models.Configuration.AttributeModel.AttributeName
  name: AttributeName
  nameWithType: AttributeModel.AttributeName
  fullName: Vasont.Inspire.Models.Configuration.AttributeModel.AttributeName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Vasont.Inspire.Models.Configuration.AttributeModel.AttributeDisplayName*
  commentId: Overload:Vasont.Inspire.Models.Configuration.AttributeModel.AttributeDisplayName
  name: AttributeDisplayName
  nameWithType: AttributeModel.AttributeDisplayName
  fullName: Vasont.Inspire.Models.Configuration.AttributeModel.AttributeDisplayName
- uid: Vasont.Inspire.Models.Configuration.AttributeModel.Profiled*
  commentId: Overload:Vasont.Inspire.Models.Configuration.AttributeModel.Profiled
  name: Profiled
  nameWithType: AttributeModel.Profiled
  fullName: Vasont.Inspire.Models.Configuration.AttributeModel.Profiled
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Vasont.Inspire.Models.Configuration.AttributeModel.Identifier*
  commentId: Overload:Vasont.Inspire.Models.Configuration.AttributeModel.Identifier
  name: Identifier
  nameWithType: AttributeModel.Identifier
  fullName: Vasont.Inspire.Models.Configuration.AttributeModel.Identifier
- uid: Vasont.Inspire.Models.Configuration.AttributeModel.SchemaStandardKeyName*
  commentId: Overload:Vasont.Inspire.Models.Configuration.AttributeModel.SchemaStandardKeyName
  name: SchemaStandardKeyName
  nameWithType: AttributeModel.SchemaStandardKeyName
  fullName: Vasont.Inspire.Models.Configuration.AttributeModel.SchemaStandardKeyName
