### YamlMime:ManagedReference
items:
- uid: Vasont.Inspire.Models.Security
  commentId: N:Vasont.Inspire.Models.Security
  id: Vasont.Inspire.Models.Security
  children:
  - Vasont.Inspire.Models.Security.MicroUserModel
  - Vasont.Inspire.Models.Security.MinimalRoleModel
  - Vasont.Inspire.Models.Security.MinimalTimeZoneModel
  - Vasont.Inspire.Models.Security.MinimalUserModel
  - Vasont.Inspire.Models.Security.ModuleModel
  - Vasont.Inspire.Models.Security.ModulePermissionHolderType
  - Vasont.Inspire.Models.Security.ModulePermissionModel
  - Vasont.Inspire.Models.Security.ModulePropertyModel
  - Vasont.Inspire.Models.Security.PermissionExtensions
  - Vasont.Inspire.Models.Security.PermissionFlags
  - Vasont.Inspire.Models.Security.PermissionModel
  - Vasont.Inspire.Models.Security.RoleModel
  - Vasont.Inspire.Models.Security.SecurityType
  - Vasont.Inspire.Models.Security.TimeZoneModel
  - Vasont.Inspire.Models.Security.UserModel
  - Vasont.Inspire.Models.Security.UserRoleAssociationModel
  - Vasont.Inspire.Models.Security.UserType
  langs:
  - csharp
  - vb
  name: Vasont.Inspire.Models.Security
  nameWithType: Vasont.Inspire.Models.Security
  fullName: Vasont.Inspire.Models.Security
  type: Namespace
  assemblies:
  - Vasont.Inspire.Models
references:
- uid: Vasont.Inspire.Models.Security.MicroUserModel
  commentId: T:Vasont.Inspire.Models.Security.MicroUserModel
  parent: Vasont.Inspire.Models.Security
  name: MicroUserModel
  nameWithType: MicroUserModel
  fullName: Vasont.Inspire.Models.Security.MicroUserModel
- uid: Vasont.Inspire.Models.Security.MinimalRoleModel
  commentId: T:Vasont.Inspire.Models.Security.MinimalRoleModel
  parent: Vasont.Inspire.Models.Security
  name: MinimalRoleModel
  nameWithType: MinimalRoleModel
  fullName: Vasont.Inspire.Models.Security.MinimalRoleModel
- uid: Vasont.Inspire.Models.Security.MinimalTimeZoneModel
  commentId: T:Vasont.Inspire.Models.Security.MinimalTimeZoneModel
  parent: Vasont.Inspire.Models.Security
  name: MinimalTimeZoneModel
  nameWithType: MinimalTimeZoneModel
  fullName: Vasont.Inspire.Models.Security.MinimalTimeZoneModel
- uid: Vasont.Inspire.Models.Security.MinimalUserModel
  commentId: T:Vasont.Inspire.Models.Security.MinimalUserModel
  parent: Vasont.Inspire.Models.Security
  name: MinimalUserModel
  nameWithType: MinimalUserModel
  fullName: Vasont.Inspire.Models.Security.MinimalUserModel
- uid: Vasont.Inspire.Models.Security.ModuleModel
  commentId: T:Vasont.Inspire.Models.Security.ModuleModel
  name: ModuleModel
  nameWithType: ModuleModel
  fullName: Vasont.Inspire.Models.Security.ModuleModel
- uid: Vasont.Inspire.Models.Security.ModulePermissionHolderType
  commentId: T:Vasont.Inspire.Models.Security.ModulePermissionHolderType
  parent: Vasont.Inspire.Models.Security
  name: ModulePermissionHolderType
  nameWithType: ModulePermissionHolderType
  fullName: Vasont.Inspire.Models.Security.ModulePermissionHolderType
- uid: Vasont.Inspire.Models.Security.ModulePermissionModel
  commentId: T:Vasont.Inspire.Models.Security.ModulePermissionModel
  name: ModulePermissionModel
  nameWithType: ModulePermissionModel
  fullName: Vasont.Inspire.Models.Security.ModulePermissionModel
- uid: Vasont.Inspire.Models.Security.ModulePropertyModel
  commentId: T:Vasont.Inspire.Models.Security.ModulePropertyModel
  name: ModulePropertyModel
  nameWithType: ModulePropertyModel
  fullName: Vasont.Inspire.Models.Security.ModulePropertyModel
- uid: Vasont.Inspire.Models.Security.PermissionExtensions
  commentId: T:Vasont.Inspire.Models.Security.PermissionExtensions
  parent: Vasont.Inspire.Models.Security
  name: PermissionExtensions
  nameWithType: PermissionExtensions
  fullName: Vasont.Inspire.Models.Security.PermissionExtensions
- uid: Vasont.Inspire.Models.Security.PermissionFlags
  commentId: T:Vasont.Inspire.Models.Security.PermissionFlags
  parent: Vasont.Inspire.Models.Security
  name: PermissionFlags
  nameWithType: PermissionFlags
  fullName: Vasont.Inspire.Models.Security.PermissionFlags
- uid: Vasont.Inspire.Models.Security.PermissionModel
  commentId: T:Vasont.Inspire.Models.Security.PermissionModel
  parent: Vasont.Inspire.Models.Security
  name: PermissionModel
  nameWithType: PermissionModel
  fullName: Vasont.Inspire.Models.Security.PermissionModel
- uid: Vasont.Inspire.Models.Security.RoleModel
  commentId: T:Vasont.Inspire.Models.Security.RoleModel
  name: RoleModel
  nameWithType: RoleModel
  fullName: Vasont.Inspire.Models.Security.RoleModel
- uid: Vasont.Inspire.Models.Security.TimeZoneModel
  commentId: T:Vasont.Inspire.Models.Security.TimeZoneModel
  parent: Vasont.Inspire.Models.Security
  name: TimeZoneModel
  nameWithType: TimeZoneModel
  fullName: Vasont.Inspire.Models.Security.TimeZoneModel
- uid: Vasont.Inspire.Models.Security.UserModel
  commentId: T:Vasont.Inspire.Models.Security.UserModel
  name: UserModel
  nameWithType: UserModel
  fullName: Vasont.Inspire.Models.Security.UserModel
- uid: Vasont.Inspire.Models.Security.SecurityType
  commentId: T:Vasont.Inspire.Models.Security.SecurityType
  parent: Vasont.Inspire.Models.Security
  name: SecurityType
  nameWithType: SecurityType
  fullName: Vasont.Inspire.Models.Security.SecurityType
- uid: Vasont.Inspire.Models.Security.UserRoleAssociationModel
  commentId: T:Vasont.Inspire.Models.Security.UserRoleAssociationModel
  parent: Vasont.Inspire.Models.Security
  name: UserRoleAssociationModel
  nameWithType: UserRoleAssociationModel
  fullName: Vasont.Inspire.Models.Security.UserRoleAssociationModel
- uid: Vasont.Inspire.Models.Security.UserType
  commentId: T:Vasont.Inspire.Models.Security.UserType
  parent: Vasont.Inspire.Models.Security
  name: UserType
  nameWithType: UserType
  fullName: Vasont.Inspire.Models.Security.UserType
- uid: Vasont.Inspire.Models.Security
  commentId: N:Vasont.Inspire.Models.Security
  name: Vasont.Inspire.Models.Security
  nameWithType: Vasont.Inspire.Models.Security
  fullName: Vasont.Inspire.Models.Security
