### YamlMime:ManagedReference
items:
- uid: Vasont.Inspire.Models.Configuration.RelationKeyName
  commentId: T:Vasont.Inspire.Models.Configuration.RelationKeyName
  id: RelationKeyName
  parent: Vasont.Inspire.Models.Configuration
  children:
  - Vasont.Inspire.Models.Configuration.RelationKeyName.Branch
  - Vasont.Inspire.Models.Configuration.RelationKeyName.DocbookHref
  - Vasont.Inspire.Models.Configuration.RelationKeyName.Fileref
  - Vasont.Inspire.Models.Configuration.RelationKeyName.Linkend
  - Vasont.Inspire.Models.Configuration.RelationKeyName.None
  - Vasont.Inspire.Models.Configuration.RelationKeyName.Translation
  - Vasont.Inspire.Models.Configuration.RelationKeyName.Xpointer
  langs:
  - csharp
  - vb
  name: RelationKeyName
  nameWithType: RelationKeyName
  fullName: Vasont.Inspire.Models.Configuration.RelationKeyName
  type: Enum
  source:
    remote:
      path: src/Configuration/RelationModel.cs
      branch: feature/NotificationDetailedMessageSupport
      repo: https://github.com/vasont-systems/Vasont.Inspire.Models.git
    id: RelationKeyName
    path: Configuration/RelationModel.cs
    startLine: 13
  assemblies:
  - Vasont.Inspire.Models
  namespace: Vasont.Inspire.Models.Configuration
  summary: "\nContains an enumerated list of relation key names.\n"
  example: []
  syntax:
    content: >-
      [JsonConverter(typeof(StringEnumConverter))]

      public enum RelationKeyName
    content.vb: >-
      <JsonConverter(GetType(StringEnumConverter))>

      Public Enum RelationKeyName
  attributes:
  - type: Newtonsoft.Json.JsonConverterAttribute
    ctor: Newtonsoft.Json.JsonConverterAttribute.#ctor(System.Type)
    arguments:
    - type: System.Type
      value: Newtonsoft.Json.Converters.StringEnumConverter
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Vasont.Inspire.Models.Configuration.RelationKeyName.None
  commentId: F:Vasont.Inspire.Models.Configuration.RelationKeyName.None
  id: None
  parent: Vasont.Inspire.Models.Configuration.RelationKeyName
  langs:
  - csharp
  - vb
  name: None
  nameWithType: RelationKeyName.None
  fullName: Vasont.Inspire.Models.Configuration.RelationKeyName.None
  type: Field
  source:
    remote:
      path: src/Configuration/RelationModel.cs
      branch: feature/NotificationDetailedMessageSupport
      repo: https://github.com/vasont-systems/Vasont.Inspire.Models.git
    id: None
    path: Configuration/RelationModel.cs
    startLine: 19
  assemblies:
  - Vasont.Inspire.Models
  namespace: Vasont.Inspire.Models.Configuration
  summary: "\nNo Key Name\n"
  example: []
  syntax:
    content: None = 0
    return:
      type: Vasont.Inspire.Models.Configuration.RelationKeyName
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Vasont.Inspire.Models.Configuration.RelationKeyName.Branch
  commentId: F:Vasont.Inspire.Models.Configuration.RelationKeyName.Branch
  id: Branch
  parent: Vasont.Inspire.Models.Configuration.RelationKeyName
  langs:
  - csharp
  - vb
  name: Branch
  nameWithType: RelationKeyName.Branch
  fullName: Vasont.Inspire.Models.Configuration.RelationKeyName.Branch
  type: Field
  source:
    remote:
      path: src/Configuration/RelationModel.cs
      branch: feature/NotificationDetailedMessageSupport
      repo: https://github.com/vasont-systems/Vasont.Inspire.Models.git
    id: Branch
    path: Configuration/RelationModel.cs
    startLine: 24
  assemblies:
  - Vasont.Inspire.Models
  namespace: Vasont.Inspire.Models.Configuration
  summary: "\nIdentifies a relation created from a branch.\n"
  example: []
  syntax:
    content: Branch = 1
    return:
      type: Vasont.Inspire.Models.Configuration.RelationKeyName
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Vasont.Inspire.Models.Configuration.RelationKeyName.Translation
  commentId: F:Vasont.Inspire.Models.Configuration.RelationKeyName.Translation
  id: Translation
  parent: Vasont.Inspire.Models.Configuration.RelationKeyName
  langs:
  - csharp
  - vb
  name: Translation
  nameWithType: RelationKeyName.Translation
  fullName: Vasont.Inspire.Models.Configuration.RelationKeyName.Translation
  type: Field
  source:
    remote:
      path: src/Configuration/RelationModel.cs
      branch: feature/NotificationDetailedMessageSupport
      repo: https://github.com/vasont-systems/Vasont.Inspire.Models.git
    id: Translation
    path: Configuration/RelationModel.cs
    startLine: 29
  assemblies:
  - Vasont.Inspire.Models
  namespace: Vasont.Inspire.Models.Configuration
  summary: "\nIdentifies a relation created from a translation.\n"
  example: []
  syntax:
    content: Translation = 2
    return:
      type: Vasont.Inspire.Models.Configuration.RelationKeyName
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Vasont.Inspire.Models.Configuration.RelationKeyName.Fileref
  commentId: F:Vasont.Inspire.Models.Configuration.RelationKeyName.Fileref
  id: Fileref
  parent: Vasont.Inspire.Models.Configuration.RelationKeyName
  langs:
  - csharp
  - vb
  name: Fileref
  nameWithType: RelationKeyName.Fileref
  fullName: Vasont.Inspire.Models.Configuration.RelationKeyName.Fileref
  type: Field
  source:
    remote:
      path: src/Configuration/RelationModel.cs
      branch: feature/NotificationDetailedMessageSupport
      repo: https://github.com/vasont-systems/Vasont.Inspire.Models.git
    id: Fileref
    path: Configuration/RelationModel.cs
    startLine: 34
  assemblies:
  - Vasont.Inspire.Models
  namespace: Vasont.Inspire.Models.Configuration
  summary: "\nIdentifies a relation created from a Docbook fileref.\n"
  example: []
  syntax:
    content: Fileref = 3
    return:
      type: Vasont.Inspire.Models.Configuration.RelationKeyName
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Vasont.Inspire.Models.Configuration.RelationKeyName.DocbookHref
  commentId: F:Vasont.Inspire.Models.Configuration.RelationKeyName.DocbookHref
  id: DocbookHref
  parent: Vasont.Inspire.Models.Configuration.RelationKeyName
  langs:
  - csharp
  - vb
  name: DocbookHref
  nameWithType: RelationKeyName.DocbookHref
  fullName: Vasont.Inspire.Models.Configuration.RelationKeyName.DocbookHref
  type: Field
  source:
    remote:
      path: src/Configuration/RelationModel.cs
      branch: feature/NotificationDetailedMessageSupport
      repo: https://github.com/vasont-systems/Vasont.Inspire.Models.git
    id: DocbookHref
    path: Configuration/RelationModel.cs
    startLine: 39
  assemblies:
  - Vasont.Inspire.Models
  namespace: Vasont.Inspire.Models.Configuration
  summary: "\nIdentifies a relation created from a Docbook href.\n"
  example: []
  syntax:
    content: DocbookHref = 4
    return:
      type: Vasont.Inspire.Models.Configuration.RelationKeyName
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Vasont.Inspire.Models.Configuration.RelationKeyName.Linkend
  commentId: F:Vasont.Inspire.Models.Configuration.RelationKeyName.Linkend
  id: Linkend
  parent: Vasont.Inspire.Models.Configuration.RelationKeyName
  langs:
  - csharp
  - vb
  name: Linkend
  nameWithType: RelationKeyName.Linkend
  fullName: Vasont.Inspire.Models.Configuration.RelationKeyName.Linkend
  type: Field
  source:
    remote:
      path: src/Configuration/RelationModel.cs
      branch: feature/NotificationDetailedMessageSupport
      repo: https://github.com/vasont-systems/Vasont.Inspire.Models.git
    id: Linkend
    path: Configuration/RelationModel.cs
    startLine: 44
  assemblies:
  - Vasont.Inspire.Models
  namespace: Vasont.Inspire.Models.Configuration
  summary: "\nIdentifies a relation created from a Docbook linkend.\n"
  example: []
  syntax:
    content: Linkend = 5
    return:
      type: Vasont.Inspire.Models.Configuration.RelationKeyName
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Vasont.Inspire.Models.Configuration.RelationKeyName.Xpointer
  commentId: F:Vasont.Inspire.Models.Configuration.RelationKeyName.Xpointer
  id: Xpointer
  parent: Vasont.Inspire.Models.Configuration.RelationKeyName
  langs:
  - csharp
  - vb
  name: Xpointer
  nameWithType: RelationKeyName.Xpointer
  fullName: Vasont.Inspire.Models.Configuration.RelationKeyName.Xpointer
  type: Field
  source:
    remote:
      path: src/Configuration/RelationModel.cs
      branch: feature/NotificationDetailedMessageSupport
      repo: https://github.com/vasont-systems/Vasont.Inspire.Models.git
    id: Xpointer
    path: Configuration/RelationModel.cs
    startLine: 49
  assemblies:
  - Vasont.Inspire.Models
  namespace: Vasont.Inspire.Models.Configuration
  summary: "\nIdentifies a relation created from a Docbook xpointer.\n"
  example: []
  syntax:
    content: Xpointer = 6
    return:
      type: Vasont.Inspire.Models.Configuration.RelationKeyName
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Vasont.Inspire.Models.Configuration
  commentId: N:Vasont.Inspire.Models.Configuration
  name: Vasont.Inspire.Models.Configuration
  nameWithType: Vasont.Inspire.Models.Configuration
  fullName: Vasont.Inspire.Models.Configuration
- uid: Vasont.Inspire.Models.Configuration.RelationKeyName
  commentId: T:Vasont.Inspire.Models.Configuration.RelationKeyName
  parent: Vasont.Inspire.Models.Configuration
  name: RelationKeyName
  nameWithType: RelationKeyName
  fullName: Vasont.Inspire.Models.Configuration.RelationKeyName
